version: '3.9'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bot_container_is
    restart: always
    env_file:
      - ./.env
    volumes:
      - .:/app
    command: ["python3", "main.py"]



